apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyndnsr53
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: dyndnsr53
        args:
        - serve
        - --provider=none  # Use none provider for development
        - --listen=:8080
        env:
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"