apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dyndnsr53-development

resources:
- ../../base

patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: dyndnsr53
- path: route-patch.yaml
  target:
    kind: Route
    name: dyndnsr53

images:
- name: quay.io/cldmnky/dyndnsr53
  newTag: v0.1-4

namePrefix: dev-

labels:
- pairs:
    environment: development
namespace: dyndnsr53-dev
